# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RwTickets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RwTickets

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'

  # TextField
  pod 'SkyFloatingLabelTextField'

  # Calendar
  pod 'KDCalendar'

  # Html Parser
  pod 'SwiftSoup'
end
